### ISSUE TITLE
Unable to access SaaS Boost

### ISSUE THREAD

**Issue by MirandaDora** [awslabs/aws-saas-boost#137]
I've successfully installed SaaS Boost and got the email (great).
However, clicking the cloudfront link, and it gives me AccessDenied:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>QRDP885QWHEZ9285</RequestId>
<HostId>q98D8eTPlYDAeWXMApYYYy/n0v12nIbMxxCkXOswx3bTCnzz2J+Q9oWD7Rvy+Dq4cLhw+OX35KU=</HostId>
</Error>
```
Checking the linked S3 bucket, it is empty (sb-dev-webs3bucket-xxxxxxx).

Checking S3 bucket policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity MYDISTRIBUTION"
            },
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::sb-dev-webs3bucket-xxxxxxx/*"
        },
        {
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::sb-dev-webs3bucket-xxxxxxx/*",
                "arn:aws:s3:::sb-dev-webs3bucket-xxxxxxx"
            ],
            "Condition": {
                "Bool": {
                    "aws:SecureTransport": "false"
                }
            }
        }
    ]
}
```

### What did you expect to happen?
Able to see SaaS Boost login page.

### What actually happened?
AccessDenied

### Environment

  - **AWS Region  :us-west-2
  - **AWS SaaS Boost Version :1.0.0**
  - **Workload OS  (Linux or Windows) : Cloud9**

### Other

--- 

This is :bug: Bug Report

**Comment by PoeppingT** [comment]
Hi @MirandaDora , during the installer there is a phase where we build the web application and upload the files to the S3 web bucket. Normally in the course of the installer, you will see a message like 
```
Build website and upload to S3
Start build of AWS SaaS Boost React web application with yarn...
Completed build of AWS SaaS Boost React web application.
Synchronizing AWS SaaS Boost web application files to s3 web bucket
Uploading 653 files to S3
```

Can you confirm that you saw those messages? Was there any error message that showed up while running the installer?

**Comment by PoeppingT** [comment]
I've done of my own investigation into Cloud9, and it looks like this is caused by a variety of things:
1. [AWS Cloud9 maintains and updates](https://docs.aws.amazon.com/cloud9/latest/user-guide/security-iam.html#auth-and-access-control-temporary-managed-credentials) an `~/.aws/credentials` file with assumed credentials on behalf of your environment that refresh every 15 minutes. AWS Cloud9 manages this file by changing its content before the credentials inside expire.
2. [We're using the `DefaultCredentialsProvider` in the SaaS Boost Installer when creating our AWS clients](https://github.com/awslabs/aws-saas-boost/blob/main/installer/src/main/java/com/amazon/aws/partners/saasfactory/saasboost/SaaSBoostInstall.java#L135-L176). The `ProfileCredentialsProvider` will likely end up being used in a Cloud9 environment ([unless system properties or environment variables have been configured](https://github.com/aws/aws-sdk-java-v2/blob/master/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.java#L68-L94), which by default they're not).
3. The `ProfileCredentialsProvider` has a [known open feature request](https://github.com/aws/aws-sdk-java-v2/issues/1754) to automatically reload failed profile credentials from disk if the profile credentials change. This has not yet been fixed.

Currently my idea is to write a wrapper around the DefaultCredentialsProvider we're already using that will recreate the underlying ProfileCredentialsProvider iff:
1. Current credentials are expired
2. The ProfileCredentialsProvider was used to retrieve them
