### ISSUE TITLE
Micro Service Implementation with SaaS Boost

### ISSUE THREAD

**Issue by avsh1617** [awslabs/aws-saas-boost#143]
Hi Team,

This is regarding implementation of Micro Services through SaaS Boost Setup. We have couple of service are designed and we have created docker image for the same. We need your suggestion to deploy these micro services through SaaS Boost Implementation.

Can this be implemented with current SaaS boost Setup.  if yes please let us know the way forward and if any documentation was prepared for the same then it would be helpful for us.

**Comment by avsh1617** [comment]
Thanks for the update, Do we have any ETA for this feature. as we are planning to implement this in our project in coming days only.

Also do we have any plan for db schema configuration per micro service.


Thanks

**Comment by brtrvn** [comment]
It will take longer than a couple of days to properly implement multi-container support. Our ETA is by end of year (hopefully sooner!). We need to make some significant changes to how the Settings and Onboarding microservices work as well as modifying some of the CloudFormation templates. Keep your eye on discussion #25 and the soon-to-be-created feature branch.

Our intent is for the existing provisioning process ("application" settings -- i.e. compute settings) plus "extensions" will now be defined as a list instead of a single unit. This means each "service" that you define for your application will be able to define its own extensions including relational databases. We currently support providing a schema definition file for database provisioning.

**Comment by brtrvn** [comment]
See #206

**Comment by HatariOS** [comment]
@avsh1617, Check out the [SaaS Boost v2 launch](https://github.com/awslabs/aws-saas-boost/discussions/206) for this use case.

**Comment by brtrvn** [comment]
Merged into `main`. Release tag for v2.0.0 will come in the next few days.
