### ISSUE TITLE
Setup issue when installing in another region

### ISSUE THREAD

**Issue by gopikrishnakolla** [awslabs/aws-saas-boost#153]
I have deployed SaaS Boost in one of my accounts in us-east-1 and it was successfull. I kicked off another installation in other account with us-west-2 region. It failed with this error "Internal error reported from downstream service during operation 'The caller reference that you are using to create a distribution is associated with another distribution. Already exists: E2O6U8DECVP5UD (Service: CloudFront, Status Code: 409, Request ID: fdf66795-74c0-4eb5-a131-267175ab3f20, Extended Request ID: null)'.". I understand that the admin console (react.js) SPA application is served from S3 via cloudfront. Any pointers to fix this?

### Reproduction Steps
1/Setup SB once successfully in one AWS account in a region (say us-east-1)
2/Try setting up SB in another AWS account in another region (say us-west-2) using same email for admin

### What did you expect to happen?
Second installation should be successful with a different cloudfront distribution

### What actually happened?
Second installation failed during creation of distribution with above error

--- 

This is :bug: Bug Report

**Comment by PoeppingT** [comment]
Hello @gopikrishnakolla , thank you for submitting this bug report! `CallerReference` is a [CloudFront concept](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_DistributionConfig.html#cloudfront-Type-DistributionConfig-CallerReference) that helps prevent accidental call duplication. We are investigating why what should be two completely different caller references from CloudFormation apparently were equal.

You can help us investigate, reproduce, and root cause by answering the following questions:
1. What version of SaaS Boost are you using? If you're on `main`, please post the shorted commit hash of HEAD on your branch.
2. Do you have any local changes to SaaS Boost?
3. Did you use the same environment name for your second SaaS Boost installation? 

Thanks in advance for your help. We're working hard on finding a workaround for you.

**Comment by gopikrishnakolla** [comment]
Thanks @PoeppingT for looking into the same. Checked my CloudTrail and see multiple invocations to create distribution as part of sb-web stack with same callerReference. Understandably starting with second call at 17:17:09 failed with DistributionAlreadyExists, though don't know why the subsequent attempts of distribution creation after 17:16:54, which didn't have any Error code. 
CreateDistributionWithTags | December 07, 2021, 17:17:13 (UTC-06:00) | admin | cloudfront.amazonaws.com | - | -
CreateDistributionWithTags | December 07, 2021, 17:17:09 (UTC-06:00) | admin | cloudfront.amazonaws.com | - | -
CreateDistributionWithTags | December 07, 2021, 17:16:54 (UTC-06:00) | admin | cloudfront.amazonaws.com | - | -

1.yeap from main, 7bcc164
2. Didn't do any changes locally
3. yes i used the same environment name (dev) for both

**Comment by PoeppingT** [comment]
@gopikrishnakolla this looks an awful lot like a side effect to recovery from yesterday's event. To confirm, can you take the following steps:
1. Using the installer, delete the new environment you created that failed.
2. Try creating it again with the same configurations.
If the original issue was tied to yesterday's AWS event, we should see a successful build.

By the way, are you unblocked on using your normal environment in us-east-1 today?

**Comment by gopikrishnakolla** [comment]
yes @PoeppingT i am unblocked. My environment in us-east-1 is working as expected. Will try to spin another SB environment and report back if all is well, in which case as you suggested should be a red-herring

**Comment by gopikrishnakolla** [comment]
Am able to successfully deploy another SB environment in another AWS account without any issues.
