### ISSUE TITLE
Creating Tenant & Deployment failed 

### ISSUE THREAD

**Issue by shashi99899** [awslabs/aws-saas-boost#203]
### Creating Tenant & Deployment failed##
When creating Provision Tenant it's  getting  failed while deployment 

[2]: http://xyproblem.info
-->

### Environment

  - **AWS SaaS Boost Version:**

**Comment by PoeppingT** [comment]
Hi @shashi99899 , tenant deployments can fail for any number of reasons. Without more information I cannot tell you exactly what has gone wrong. Here are some tips for debugging failed tenant deployments:

1. Have you uploaded Docker images into the ECR repository? Go to your AWS Console, search for ECR (Elastic Container Repository) and click on repositories. <img width="687" alt="Screen Shot 2022-03-10 at 16 52 30" src="https://user-images.githubusercontent.com/4009272/157780615-571fd34a-a326-49eb-a22a-6e665fc9baf0.png"> You should see repositories listed to below something like this screenshot. Do those repositories have images? Click on the repository name.  There should be images listed here. <img width="725" alt="Screen Shot 2022-03-10 at 16 55 22" src="https://user-images.githubusercontent.com/4009272/157780883-52c0dfa8-26a9-4214-bc53-d03f9f2997f9.png"> If not, you can push to the repository using the Docker commands displayed when you click "View Push Commands".
2. Have you viewed the tenant onboarding stack? Go to your AWS Console, search for CloudFormation, and click "Stacks" on the left. In the list there should be a stack name like `tenant-########` that represents the parent stack for the tenant you tried to provision. Does that stack exist? If it shows that the stack create failed, you can inspect the reasons for this by clicking on the stack and navigating to the "Events" tab. Scrolling down will show you every event that was generated by that stack, allowing you to inspect failures. Some event failures may be due to previous failures, be sure to be thorough in your investigation.
3. If the tenant onboarding stack was successful, try viewing the Logs for your application. These are published to CloudWatch. Go to your AWS Console, search for CloudWatch, and click on Log Groups on the left. Type `/ecs` in the search box to view all log groups for your ECS clusters. What recent log events have there been for that tenant? Is there any indication of failure?

Thanks for downloading SaaS Boost, and good luck with your troubleshooting! Please do not hesitate to open a Pull Request against our documentation if there are changes you want to be made.

**Comment by PoeppingT** [comment]
Hi @shashi99899 , it has been over a month without comment on this issue. Can you clarify what problem you are having? I will close this issue after another week of no response.
