### ISSUE TITLE
error shows up in cloudwatch when onboard tenants: Can't find onboarding record for tenant tenant

### ISSUE THREAD

**Issue by qwudssd** [awslabs/aws-saas-boost#231]
Tenants could not be successfully deployed and there is an error in onboarding-events in CloudWatch:

<img width="1321" alt="Screen Shot 2022-06-03 at 11 47 18 AM" src="https://user-images.githubusercontent.com/104920467/171900481-afab1740-4262-491f-b97b-b48652e0e36b.png">

### Environment

  - **AWS SaaS Boost Version:** Saas main branch

**Comment by qwudssd** [comment]
thanks for the response! hope the info below helps
1. environment name: dev-t15
    Region: us-west-2
2. tenant’s name: test
    Used the provision tenant feature in the user interface to provision the tenant
3. Haven’t made any changes in the local SaaS Boost
4. the entire log that has the error msg:
<img width="1351" alt="Screen Shot 2022-06-03 at 2 56 20 PM" src="https://user-images.githubusercontent.com/104920467/171941533-0d2a9f52-040e-493a-8245-595146d76652.png">

5. the event that was being handled is: OnboardingService - Handling Onboarding Deployment Pipeline Changed

**Comment by PoeppingT** [comment]
This is happening due to the `-` character in your environment name. To unblock yourself immediately, create a new environment without that character to continue testing and we will address this bug when we can.

**Comment by qwudssd** [comment]
okay i see. Thanks!

**Comment by rnlduaeo** [comment]
Please review the PR. https://github.com/awslabs/aws-saas-boost/pull/240

**Comment by rnlduaeo** [comment]
@Poepping When you change this bug, please make sure that env name is also used in athena query table, when I manually changed the split function in /aws-saas-boost/services/onboarding-service/src/main/java/com/amazon/aws/partners/saasfactory/saasboost/OnboardingService.java line 1111 > tenantId = pipeline.split("-")[3]; 
to tenantId = pipeline.split("-tenant-")[1].split("-")[0]; 
The tenant onboarding works, but the request count metric values were not fetched in the 'Usage' page. This was due to the fact that env name is also used in athena query table, I thought about wrapping it in double quotation but was not sure about any downstreaming effect of changing that. Please consider this as well when you fix the bug.
