### ISSUE TITLE
tenant successfully deployed, but can not connect to the internal service

### ISSUE THREAD

**Issue by qwudssd** [awslabs/aws-saas-boost#234]
Have successfully deployed a tenant, but still having trouble connecting to the internal service. 
Method: using http to connect to the internal service and getting the host and port name from these two environment variables: SERVICE_TELLREAD_HOST, SERVICE_TELLREAD_PORT

<img width="493" alt="Screen Shot 2022-06-09 at 11 06 45 AM" src="https://user-images.githubusercontent.com/104920467/172880420-0fe52876-18d8-4590-a0c1-526eff8e8cca.png">
<img width="1386" alt="Screen Shot 2022-06-09 at 10 51 37 AM" src="https://user-images.githubusercontent.com/104920467/172880994-15fa1815-57ee-4e88-983c-7edd35df2076.png">

### Environment

  - **AWS SaaS Boost Version:**  main branch

**Comment by qwudssd** [comment]
and there is this warning in the browser console

<img width="856" alt="Screen Shot 2022-06-09 at 11 18 34 AM" src="https://user-images.githubusercontent.com/104920467/172883081-bd7fcc33-07cb-4fcf-9e8b-79140269bcc2.png">

**Comment by brtrvn** [comment]
My guess is that you're not resolving DNS because you're executing this code _**in the web browser**_ rather than in the Docker container inside the AWS VPC the service is deployed to. These internal/private services are just that - private. There will be no public Internet route to those services. Will have to do some more investigation to confirm that this is the issue, but that's my guess.

If I'm right, you have 2 options:
- Make the tellread service public and set a unique URL path prefix for it (e.g. `logs/*`)
- Make another public _backend_ service that your React app calls that runs on the serverside and have that make the calls to the private tellread service.

**Comment by qwudssd** [comment]
@brtrvn thanks for the response! can you elaborate bit more about how the Service Addressable Path work if there are two public services? will they have the same domain name?

**Comment by brtrvn** [comment]
When you have multiple **public** services, they are all addressable from the single domain name for that onboarded tenant. We route requests to the different services based on URL path prefix. Your "default" service should always use a path prefix of `/*`. Additional public services should define paths subordinate to the root. For example `/api*`. Or, in your case it might be `/logs*`.

I am no JavaScript expert, but you could imagine a server side tellread service that might expose `logs` endpoints that could look something like this...
```
const express = require('express');
const app = express();
const port = 3000;

app.use(express.json());

// The ALB needs a health check path and this path isn't
// interpreted by the listener rules defined on the target
// group, so you don't need to prefix it with this service's
// path prefix
app.get('/health', function(req, res) {
	res.status(200).send();
});

// Every other endpoint this service is responsible for needs
// to be prefixed with the path defined in the listener rule
const pathPrefix = '/logs';

// Equivalent to /logs
app.get(pathPrefix, function(req, res) {
	res.send({message: "Log reader service ready"});
});

// Equivalent to /logs/read/<id>
app.get(pathPrefix + '/read/:id', function(req, res) {
	res.send({message: "Log reader service API invocation for " + req.params.id});
});

// Start the service
app.listen(port, function(err) {
	if (err) {
		console.log(err);
	}
	console.log("Reader service listening on port " + port);
});
```

This would assume that you've configured a 2nd public service called "reader" and set its path to `/logs*` and its port to `3000` and its health check to `/health`

Now, anyone pointing their web browser at TENANT_SUBDOMAIN.YOUR_DOMAIN/ will get your React app and anyone pointing their web browser at TENANT_SUBDOMAIN.YOUR_DOMAIN/logs will get responses from the other Docker container.

The key to making this work is that the "reader" service in our example must prefix all its GET/PUT/POST/DELETE etc routes with the path you configured for the service because Amazon Application Load Balancers don't do URL rewriting for target groups.

It's also important to note that public services are indeed public. So, if you don't want your users to be able to directly invoke the tellread service from the Internet without going through your front end React app, then you are going to have to make a lightweight "proxy" service that runs on the server side to invoke the tellread private service on behalf of the frontend. This is simply a limitation of whether the JavaScript is being executed outside your AWS account in a customer's web browser or inside the account in a Docker image running in ECS.

In the example above we could make the tellread service "private" so users on the Internet wouldn't be able to invoke it without going through your React app _because the Node Express code is "server side"_ you could change the implementation of the `GET` for /logs/read/<id> to invoke a private service. Might look something like
```
let readerServiceUrl = 'http://' + process.env.SERVICE_READER_HOST + ':' + process.env.SERVICE_READER_PORT + '/logs';
const readerServiceRequest = async() => {
    try {
        var logId = 57;
        const readerServiceResponse = await axios.get(readerServiceUrl + '/read/' + logId);
        return (readerServiceResponse.data.result);
    } catch(err) {
        console.error(err);
    }
}

let readerServiceResult = await readerServiceRequest();
if (readerServiceResult) {
    // do something with the response from the other service
}
```
Hope this helps. Excited to see you succeed with SaaS Boost.

**Comment by qwudssd** [comment]
@brtrvn Thank you so much! This is really helpful! We are now able to connect one service to another if the two are both public. We'd like our tellread service to stay private so now we are creating an intermediate service between the client and tellread.
