### ISSUE TITLE
InvokeRDSBootstrapDatabase throws the error while trying to connect to database

### ISSUE THREAD

**Issue by rnlduaeo** [awslabs/aws-saas-boost#241]
Database initialization functionality in SaaSBoost tried to access poastgresql and threw an exception. I got below error message in rdsbootstrap lambda log group.
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/5877925/176625587-81eaf65b-7581-4f20-b902-dff4b55a1732.png">

### Reproduction Steps

1) upload .sql file(UTF-8 encoded) in rds appconfig screen.
2) try to onboard a tenant, you will see the above error message.

### What did you expect to happen?

At least the database connection should be established, even though some syntax error might be occurred.

### What actually happened?

Can't connect to database host

### Environment

  - **AWS Region  :** ap-northeast-2
  - **AWS SaaS Boost Version :** Version 798371c
  - **Workload OS  (Linux or Windows) :**  linux

### Other

--- 

This is :bug: Bug Report

**Comment by bella-kwon** [comment]
For someone who encounters this error like me.
Here's the root cause I found -
ResultSet had been closed within try block(line: 187) in [RdsBootstrap.databaseExists](https://github.com/awslabs/aws-saas-boost/blob/798371c40b032e097d51ac9e57292af78bc201c4/resources/custom-resources/rds-bootstrap/src/main/java/com/amazon/aws/partners/saasfactory/saasboost/RdsBootstrap.java#L181) before trying rs.next() (line:194)
I So I just moved while block while (rs.next()) {  into the try block as follows. You can fix this temporarily by changing this part and try to run it.
![image](https://user-images.githubusercontent.com/43110337/176792754-4abcc5cf-0b8d-4c19-9004-e6bf2b0d62af.png)

Of course, I understand that there will be many considerations for supporting DB engines from the team's perspectives.

I wrote this to reduce the # of developers who are wandering until then.
