### ISSUE TITLE
cloudformation stacks for the deployed services failed while onboarding tenants

### ISSUE THREAD

**Issue by qwudssd** [awslabs/aws-saas-boost#356]
we've deployed three services on the saas boost app, Client, Proxy and Tellread. But while provisioning a tenant, two of the three cloudformation stacks for the three services came back failed with this error msg and the one for the service tellread succeeded.

sb-dev-ecs-instance-tenant-ccb402c3 already exists in stack arn:aws:cloudformation:us-west-2:042377184132:stack/sb-dev-tenant-ccb402c3-app-tellread-2452RWY4BM53/688f9a80-40ea-11ed-9e81-0a1242b2c085

not really sure how to progress thru this, thanks

saas boost branch: the latest version from master

**Comment by brtrvn** [comment]
Thanks for the report @qwudssd. We believe this only happens when you configure multiple services with the EC2 launch type. Looks like we're suffering from this issue https://github.com/aws/containers-roadmap/issues/631#issuecomment-1135280791.

Currently working on a fix using a custom resource to work around CloudFormation's limitations with Capacity Providers.
