### ISSUE TITLE
codepipeline timeout issue

### ISSUE THREAD

**Issue by qwudssd** [awslabs/aws-saas-boost#425]
i have three services and two of them are successfully deployed and the other is having the timeout error. Im trying to debug this error, but didn't really find the error message.
<img width="1485" alt="Screen Shot 2022-11-17 at 10 18 52 AM" src="https://user-images.githubusercontent.com/104920467/202485903-c426f62a-0227-4f7e-b92f-c1ffdea715f7.png">

branch:latest main

**Comment by brtrvn** [comment]
Given the pipeline stages in your screenshot above, the problem is usually with your container stabilizing during ECS deployment. I would check 2 common reasons: 1 - your code throws an uncaught exception/error during startup and fails to deploy. 2 - your code does launch ok, but the health check URL is incorrect or non responsive or it takes too long for your container to launch and the load balancer reports to ECS that the container isn't healthy.

I would go into the ECS console, select the cluster for the tenant that is not succeeding, then select the Tasks tab and select one of the Stopped tasks, then select the Logs tab and you should be able to see some more details about what's going on.

**Comment by qwudssd** [comment]
thanks so much for the reply! I've fixed the issue, it was because the health check url was not quite right

**Comment by brtrvn** [comment]
Glad it was an easy fix!
