### ISSUE TITLE
Not able ot create more that 5 tenant in AWS SaaS Boost. 

### ISSUE THREAD

**Issue by SudhaGanesanAkilandam** [awslabs/aws-saas-boost#437]
AWS SaaS Boost create a vpn service for each tenant, so that our region 5 vpn only allotted so that we are not able to create more than 5 tenant.

**Comment by PoeppingT** [comment]
Hi @SudhaGanesanAkilandam , assuming you are speaking of the VPC created for each individual tenant (since SaaS Boost does not use AWS VPN) you can increase the limit of VPCs per region in your account by following the link on [the AWS VPC documentation](https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html).

**Comment by hellraiserii** [comment]
Hi @PoeppingT, we also hit VPC limit count and requested to double it.

Is there a reason VPC limit starts that low by default(5) in AWS accounts? Is there a hard limit for VPCs we should care about?

**Comment by PoeppingT** [comment]
@hellraiserii That is a better question for the VPC team through AWS support. A likely answer is simply so that the VPC team can better plan for usage changes.
