### ISSUE TITLE
onboarding status still appears as deploying without any issues showing in codepipeline

### ISSUE THREAD

**Issue by qwudssd** [awslabs/aws-saas-boost#471]
<img width="1515" alt="Screen Shot 2023-01-30 at 10 46 56 AM" src="https://user-images.githubusercontent.com/104920467/215525666-75e15f91-a71b-4997-97c6-2070563804de.png">
<img width="1389" alt="Screen Shot 2023-01-30 at 10 47 12 AM" src="https://user-images.githubusercontent.com/104920467/215525700-1a30f822-7dd8-4bb5-b2c3-da6ef7808f74.png">

**Comment by PoeppingT** [comment]
Hi @qwudssd , it's possible your ECS cluster has never actually successfully started, due to some startup error in the container software. If that were the case CodePipeline would show that the deployment to ECS did successfully complete (meaning the ECS cluster is now using the new version of your container), but ECS may be continually restarting the container either due to errors or due to failed health checks. 

You can check the ECS cluster logs by going to CloudWatch in your AWS Console, selecting LogGroup on the left, and finding the LogGroup(s) titled `/ecs/sb-${environment}-*`. If there is an obvious error there, ECS will destroy those containers when they exit and continually try to create new ones. 

If there is no obvious error, it is also possible you misconfigured your health check endpoint for that SaaS Boost service. To check this go to ECS in your AWS Console, click into your ECS cluster, and inspect your services to understand which might be going wrong. I would draw your attention in particular to the `Logs` and `Deployments and Events` tabs to get some more information about what might be happening.

**Comment by qwudssd** [comment]
okay, i see. Thank you!
