### ISSUE TITLE
File system settings for FSX with Windows workload does not get saved

### ISSUE THREAD

**Issue by 4patelr** [awslabs/aws-saas-boost#90]
I configured an application for Windows and when I try to configure the File system the settings are not being saved. 

### Reproduction Steps

1. Setup a Windows host in the Application page.
2. Deployed a tenant
3. Deleted a tenant
4. Tried to setup File system in the application page
5. Settings do not save

### Environment

  - **AWS Region  :** us-east-1
  - **AWS SaaS Boost Version :**
  - **Workload OS  (Linux or Windows) :**. Windows

### Other

--- 

This is :bug: Bug Report

**Comment by 4patelr** [comment]
The workaround for this is to toggle the O/S to Linux and then back to Windows on the Application config page before entering the file system details.

**Comment by tobuck-aws** [comment]
The problem is that somehow the container OS was set without setting the `fileSystemType` on the config object. There's downstream logic that looks at `fileSystemType` to determine which configuration to send (either FSX or EFS), and because it was unset, neither was sent. I changed the code to default the `fileSystemType` to FSX if containerOS is initially set to Windows, and EFS if linux. Toggling OS after this should do the right thing as there's already a listener on the radio button that changes `fileSystemType` accordingly.
